### ISSUE TITLE
Error when attempting to launch script/server

### ISSUE THREAD

**Issue by thomasthechan** [maddox/wallop#69]
I get this error:

Failed to match sequence (ALL_SPACE (TABLE / TABLE_ARRAY / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 5 char 1.
`- Don't know what to do with "port = “88" at line 5 char 1.
/Users/MoyChan/wallop/lib/wallop.rb:54:in `expand_path': no implicit conversion of nil into String (TypeError)
	from /Users/MoyChan/wallop/lib/wallop.rb:54:in `transcoding_path'
	from /Users/MoyChan/wallop/lib/wallop.rb:59:in `setup'
	from /Users/MoyChan/wallop/app/boot.rb:22:in `<top (required)>'
	from app/app.rb:2:in `require'
	from app/app.rb:2:in `<main>'

I'm EXTREMELY green and can not for the life of me figure this out. Help!

**Comment by tmm1** [comment]
Your configuration file is using a "smart-quote" instead of a regular quote. Try editing it with a different editor.

**Comment by thomasthechan** [comment]
YOU. ARE. ELECTRIC. Thanks!
